#!/bin/bash
TEMPO_A=10; 
for((i = 1; i<= $1; i++)) do
	./split $i wikipedia.txt
	echo "$i " >> time.txt
	TEMPO=$(./timediff.bash $2 './large $i')
	echo "$i $TEMPO"

	result=$(awk -vn1="$TEMPO" -vn2="$TEMPO_A" 'BEGIN{print (n1>n2)?1:0 }')
	echo "$result"
	if [ "$result" -eq 1 ]; then
		break
	fi
	TEMPO_A=$TEMPO
done 
